language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlabllc"
  - MAIN_BRANCHES="master develop"
  - secure: "qxDU6nKLa3wre/ZC7QB42bj5/nmR6z/F3t93oEefqVVbbHx9MwFKr8vlVRRqCyj5JXzGrMGQMBByCwy/IUlXnIjtumSc03XB1DhXsGY8FiAj3/xMv7xcLPJwE0EMkrVatF/iZwaK7Kjtzqj7AIi3cKiunYoqO2zslm3ObenzY4c0BRCjfjhXvEr8TxRtSePsl8kMt8dqSHQAx33c++GMqzB3HRKWbEk5tLlx3EbQpij7bkdJlh8UwPHEUBJVHGJ1Ze4LJ15x12964wFVVIkcmi4qH1PuP0lxSX1rrxT7Sdj8IloB45eGXAeTYWrPuPtooMcU+wgEovWM5fuj7FUg+0tDLNPQKhWVa6Mwyibmi/lZOEd3sDtP52Lo/4KmjW0DoY0BYDPJgaI+b1APl3s8DrDG0zyAvV0EM+cE/TyLdhk5Wy19E9D4b4FLYdsiCGADpPu7NrB9X5MA9pmyyHgobMnBbARwhgv72JWLv0L+fRm2PoeQeKpsYICLz7rQrQSfjvMggVkXQFaR1lw7rTvzVCQv0IqbzO9N/o2Q57oLqyrhO8wp5Jpq6JPnc3hdBHOMlKAj04wmVOwfJVnN5Bky4DwKtl8qWKP18hdbUAfgVpYIOWMu84yuWauatdL2Aiy34nyDgH/ilCIeOYF01EVQo5qLIhW+wZT2zXpTJg2xkdQ="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- "./bin/version-increment.sh"
- "./bin/build.sh"
- "./bin/start.sh"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs uaddresses.web
  --details --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_failure:
- docker logs uaddresses.web
after_success:
- "./bin/ci/push.sh"
