language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlabllc"
  - MAIN_BRANCHES="master develop"
  - secure: "oXf01EUIxvpWQHwuGJtXAYUOaCRiW84Whd9rb4rU6GbJfCWn5lrAI6S15yG6+cVCeUEGfYZbw2Lgct9049uR2lgOO2YYY2AS/oheIYGmXCLKJwYSVp4DvQmLmeFinF6/sEd9VgWZULOCEeNxGSbIK+uqIYuJ/O208R42o7EqZvws6xRDZwPybbh3cpSxnXgdLDn7IujKSIbWe/xyhxJFwzcdWAJpHOecH4hjSyzwteGCP5VlBJjl+3mG2E7M209b27oO7rTz0WJMDb6zkjcaL2l9L0MIMLlIDvy+wKwOyYX5ennuKMSq8oJEGeNVmqDqbMZnMDWC7sibDCIQdO+GyZ+K5B4d7tGA1MRxYhtqQw81uz7GcPvBqI4p1RKqiaorHgad/fwLg/SAI7Qa9GEXw7FXnbNB8uKJHfGvn8PaS2747KZiSNFpwnuu9vBKw3jdpj3S+XrkMPJ3z7q5tEf0o0990oDWJhZLaK+ibPewL/OGpb3MFNh2oHC0Y92xwQ733h0bD2RLxqJybuyuFu799PNlDCCKb931sKRw0nuytEfj4xrf+2XtEt16BNd5gTtVR1jYMqZalver5AXTVFfFei468IVShHaOq+3Jn4ghenSDW144yQKT9ECHwjQp8yhnELfG6Z96ZZG/rKW3nTwZiL1TPWHigJlgPX9x4moav+A="
  - secure: "q8mR2BjGnhYMfnKUdsu9/BJPGX+i34GUJWKwnFik3We4emxctcQkerxpscrVrNovIFsNAF9+LQpdLIsK9frZVGjcE4wa/xeXATg5OrTDEtByX+LzHzfAYI6HwfzrZs1NCjyJMW1FKOXbCvTE++ZT9PvRdDlNASTJIXPAwtJ/BXzTQr0qMJja+8NeUw1Rt2lkbFRBNy2aMm3TkSYiuhqMxe/wgkduCwszUZtgeremp38jSe76TNG32qSaIdH0vs4WPJpdoUtNPdAOOfTwnAR2KsOoyQpLfea+VtqRDACALdP6+UvdwQJZtYapFzTNmpcIfXIvauMksBtuFbyZyMSQaGV4a3sR4n6iOEr0Xwpx6nKGdpyghVV24HdkuLJIJ8mK+2bAMzvmLudjXsK6bbMyFJvYAISKi5zRVK118JQpZPQTW9egEGPxXTwfxSg/UVb/THnhgG5gV1VseL+9uD4HTFsMV0GgKHwjPIhf0PuWKgIpZhM39Cc9s/2pCYsX5+EMddwAt8nkqle+YJWKyEwyqeg+jCYPXYtIAgAgNq22ljNVjIO4s3oIilJuN2AS7F69K4cEiMPUNQVav+mzpJFPbUvxFssDgCZT0QGYb4zDFNpgU061vL6ax9/92FJazdm8G58GHLgIJF9pOPd98MrD+pMI2c+c768rnaui7d4sflM="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- "./bin/version-increment.sh"
- "./bin/build.sh"
- "./bin/start.sh"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs uaddresses.web
  --details --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_failure:
- docker logs uaddresses.web
after_success:
- "./bin/ci/push.sh"
