language: node_js
services:
- docker
cache:
  directories:
  - "~/.nvm"
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="nebo15"
  - MAIN_BRANCHES="master develop"
  - secure: THJUXwPivUSJLPLWfTWM2oySXrfcwdcCTej4wy9PIEVUYDFzTfaLkRIQTkouyQDFN54FbNB1vfmvDmCT/nThjOfG84sgX6BfTh5ZKYU6GigUfQ84aUoxmKBzOhATn71IZ6xsne/KC2tkSiq+rq2Txm7ncPPoNcvHvESyCVAS278cMmrQK7pwv/MTw3Kha/nup62/IvTQC0/yd9YPNQxwbPuevC2XM4Y0SXDAxjb5n2Np7l22b6KpyqAkMMAE+TIEfgppoqfj6cElvYTg2m29sIcpLffXLJxeVkwBkWn0Wqv82phjGRpTlFFHCSq7meq7jiNhmPYODWb8oUHxRaScZ9VbI6oPo7bQET1mezYs3pkWTiTt0x0UES5oo4rRVjpsrhmsNzC8ThwEN3/EU5w3whyBA8JmUxQxXce2kbeTIhBRA1Jqlr3gbnQIJKOmwt8s31hPC9iEULIrlm2iF5bFWHMb4yE1mxYm1BxyQdTQJcBN592IFj83L7GxnVikd96+208FgVbDBbPsl/qFQ1QAKh20mIhrJOPgiHzpEXEaoprnXG1a7tsegRvlsxH0dM9OXv099T4Gbk5uZaivV3aO1OvixF25hkh1Zy0naWMFBhMRnE1zipFj8uL8HUWadbBank0oQcWBcPCaMLeCtXGDklEeD4GdeWNKu+daUh5IBQA=
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- "./bin/version-increment.sh"
- "./bin/build.sh"
- "./bin/start.sh"
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs uaddresses.web
  --details --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_failure:
- docker logs uaddresses.web
after_success:
- "./bin/ci/push.sh"
