name: uaadresses-web CI

on:
  push:
    branches: 
      - ci-test
      
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [11.x]
        
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm -v
      - run: npm install
      - run: sudo npm i -g standard-version
      - run: npm install karma --save-dev
      - run: npm install karma-jasmine karma-chrome-launcher jasmine-core --save-dev
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
      - run: npm run lint || exit 1
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          
      - name: Set image tag
        id: vars
        run: |
          echo "name=image_tag::$(standard-version -m "fix: publish %s [ci skip]" --dry-run | grep 'release v' | awk -Frelease '{ print $2 }' | xargs)" >> $GITHUB_OUTPUT
          echo "name=project_name::$(cat "package.json" | grep name | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')" >> $GITHUB_OUTPUT
          echo "name=timestamp::$(date +'%s')" >> $GITHUB_OUTPUT
          
      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: eu.gcr.io/ehealth-162117/${{ steps.output.project_name }}:${{ steps.output.image_tag }}
          
      - run: |
          git config --global user.email "cub4lt@gmail.com"
          git config --global user.name "Volodymyr Shvaiko"
          standard-version -m "chore(release): publish %s [ci skip]"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/edenlabllc/uaddresses.web.git
          git push --follow-tags origin master
        continue-on-error: true
